version: '3.7'
services:
  application:
    build:
      context: .
      target: qa
    environment:
      - DB_DSN=mongodb://database:27017
      - SHOPIFY_APP_SECRET=fa5c40f68b1f6df5bc460158de97c7cf
    links:
      - database
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
  database:
    image: mongo
    ports:
      - 27017:27017
