name: QA

on: workflow_dispatch

jobs:
  build:
    name: QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Run QA
        run: |
          sed -i 's/target: application/target: qa/g' docker-compose.yml
          docker-compose build
          docker-compose up application
